# This is a basic workflow to help you get started with Actions

name: Create and upload binary into release

# Controls when the action will run. 
on:
  release:
    types: [created]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Resolve release version
        run: echo "TAG=$( git describe --tags --abbrev=0 HEAD )" >> $GITHUB_ENV

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew shadowJar publish --info

      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/libs/pages-processor-*.jar'

      - name: Set docker tag label for git tags
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "DOCKER_TAG=$( echo $GITHUB_REF | cut -d / -f 3- )" >> $GITHUB_ENV

      - name: Print parameters
        run: echo "image_tag=${{ env.DOCKER_TAG }} reference=${{ github.ref }}"

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.4.1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Build and push Docker imag
        run: TAG=andriyg76/pages-processor:${{ env.DOCKER_TAG }} &&
          GITHUB_TAG=ghcr.io/${{ github.repository }}:${{ env.DOCKER_TAG }} &&
          docker buildx build --platform linux/amd64 . --file Dockerfile --tag $TAG  --tag $GITHUB_TAG --push
